pipeline {
  agent any
  options { timestamps() }

  parameters {
    choice(
      name: 'TARGET_ENV',
      choices: ['dev', 'staging', 'prod'],
      description: 'Select environment to deploy'
    )
    booleanParam(name: 'AUTO_APPROVE', defaultValue: true, description: 'Auto approve Terraform apply')
  }

  environment {
    AWS_REGION = "ap-south-1"
    AWS_CRED   = "aws-dev-iam"   // Using same IAM for demo
  }

  stages {

    stage("Checkout") {
      steps { checkout scm }
    }

    stage("Show Environment Selection") {
      steps {
        script {
          echo """
          ✅ Selected Environment: ${params.TARGET_ENV}
          📂 Directory: webapp-iac/envs/${params.TARGET_ENV}
          🧾 Var File: ${params.TARGET_ENV}.tfvars
          """
        }
      }
    }

    stage("Terraform Init + Plan + Apply") {
      steps {
        withAWS(region: AWS_REGION, credentials: AWS_CRED) {
          dir("webapp-iac/envs/${params.TARGET_ENV}") {

            sh """
              terraform init
              terraform validate
              terraform plan -var-file=${params.TARGET_ENV}.tfvars -out=tfplan.bin
            """

            script {
              if (params.AUTO_APPROVE) {
                sh "terraform apply -auto-approve tfplan.bin"
              } else {
                sh "terraform apply tfplan.bin"
              }
            }
          }
        }
      }
    }
  }

  post {
    always {
      script {
        sh """
        cd webapp-iac/envs/${params.TARGET_ENV} && terraform output || true
        """
      }
    }
  }
}
